import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int boys = 0;
		int girls = 0;
		double sum = 0;
		double random = 0.5;
		int family2= 0;
        int family3= 0;
        int family4ormore= 0;
		for (int i = 1 ; i <= T ; i++)
		{
            while ( boys == 0 || girls == 0)
		{
			random = generator.nextDouble();
			if (random < 0.5)
			{
				boys++;
				//System.out.print("b ");
			}
			else 
			{
				girls++;
				//System.out.print("g ");	
			}
			
		}
		if ( (girls + boys) == 2 ) family2 = family2 + 1;
		else if ((girls + boys) == 3 ) family3 = family3 + 1;
		else family4ormore = family4ormore + 1;
		sum = sum + girls + boys;
		girls = 0;
		boys = 0;
		}
		System.out.println("Average: " + (sum / ((double) (T))) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + family2);
        System.out.println("Number of families with 3 children: " + family3);
		System.out.println("Number of families with 4 or more children: " + family4ormore);
        if (Math.max(Math.max(family2, family3),family4ormore)==family2)
             System.out.println("The most common number of children is 2.");
        else if (Math.max(Math.max(family2, family3),family4ormore)==family3)
		     System.out.println("The most common number of children is 3.");
        else System.out.println("The most common number of children is 4 or more.");
        //System.out.println("You made it... and you now have " + (girls + boys) + " children");   
	}
}
